# Generated by Django 2.2 on 2020-04-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='this is an author'),
            preserve_default=False,
        ),
    ]
