# Generated by Django 2.2 on 2020-04-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='las_name',
            new_name='last_name',
        ),
    ]
